### PR TITLE
Fixing presence icon anchoring to the middle of the room icon

### LINKED ISSUE #5489: Presence indicator centered over profile photo
### Steps to reproduce

markup_89 (1)

The presence indicator is covering up the profile photo.

#### What did you expect?
Presence indicator should be located in the bottom right.

### Your phone model

Pixel 6 Pro

### Operating system version

12

### Application version and app store

Element v1.4.4

### Homeserver

Synapse 1.53

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by ouchadam**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Introduces a second shield view, anchored to the room title for use when the presence indicator is present.

## Motivation and context
 
Fixes #5489, wrong presence indicator alignment.

This is an intermediate bug fix for the presence indicator anchoring to the center of the room icon. Ideally we'll have a second iteration once design is available :crossed_fingers: 

## Screenshots / GIFs

| | BEFORE | AFTER |
| --- | --- |  --- |
| NO PRESENCE |Screenshot_20220322_132042|Screenshot_20220322_123446
| WITH PRESENCE |Screenshot_20220322_132001|Screenshot_20220322_123522

## Tests

- Open a room with a user who has presence enabled
- See the top app bar has a misaligned presence indicator 

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s): Android 10

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt [hunk 1]
```diff
@@ -1613,11 +1613,10 @@ class TimelineFragment @Inject constructor(
...
                 views.includeRoomToolbar.roomToolbarTitleView.text = roomSummary.displayName
                 avatarRenderer.render(roomSummary.toMatrixItem(), views.includeRoomToolbar.roomToolbarAvatarImageView)
-                views.includeRoomToolbar.roomToolbarDecorationImageView.render(roomSummary.roomEncryptionTrustLevel)
-                views.includeRoomToolbar.roomToolbarPresenceImageView.render(
-                        roomSummary.isDirect && matrixConfiguration.presenceSyncEnabled,
-                        roomSummary.directUserPresence
-                )
+                val showPresence = roomSummary.isDirect && matrixConfiguration.presenceSyncEnabled
+                views.includeRoomToolbar.roomToolbarPresenceImageView.render(showPresence, roomSummary.directUserPresence)
+                val shieldView = if (showPresence) views.includeRoomToolbar.roomToolbarTitleShield else views.includeRoomToolbar.roomToolbarAvatarShield
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt:1618]: weird to have the shield at a different place depending if the presence is available or not...
We definitely need to iterate with design team, as you said

**Review by ariskotsomitopoulos — APPROVED** [review]
Seems fine, keep in mind there might be conflicts with this [PR](https://github.com/vector-im/element-android/pull/5583)

File: vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt (hunk 1 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt:1618]: agreed, iOS and web also handled these badges differently
