### PR TITLE
Voice Broadcast - Handle exceptions during playback

### LINKED ISSUE #7829: Crash on voice broadcast playback
### Steps to reproduce

1. Listen a voice broadcast
2. Move around the middle of the broadcast with the slider

### Outcome

The application crashed

```
2022-12-20 15:57:15.200 27473-27473/im.vector.app.debug E/VectorUncaughtExceptionHandler: FATAL EXCEPTION Element Build : 40105142
    Element Version : 1.5.14-dev [40105142] (G-31540e6d-2022-12-19 19:17:35 +0100)
    SDK Version : 1.5.14 (31540e6d)
    Phone : Pixel 6a (9244662 13 REL)
    Memory statuses 
    usedSize   96 MB
    freeSize   40 MB
    totalSize   137 MB
    Thread: main, Exception: java.io.IOException: Prepare failed.: status=0x1
        at android.media.MediaPlayer._prepare(Native Method)
        at android.media.MediaPlayer.prepare(MediaPlayer.java:1309)
        at im.vector.app.features.voicebroadcast.listening.VoiceBroadcastPlayerImpl.prepareMediaPlayer(VoiceBroadcastPlayerImpl.kt:308)
        at im.vector.app.features.voicebroadcast.listening.VoiceBroadcastPlayerImpl.access$prepareMediaPlayer(VoiceBroadcastPlayerImpl.kt:47)
        at im.vector.app.features.voicebroadcast.listening.VoiceBroadcastPlayerImpl$prepareMediaPlayer$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
        at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1413)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318)
        at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856)
        at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:806)
        at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:92)
        at kotlinx.coroutines.CompletableDeferredKt.completeWith(CompletableDeferred.kt:61)
        at org.matrix.android.sdk.internal.session.DefaultFileService.downloadFile(DefaultFileService.kt:213)
        at org.matrix.android.sdk.internal.session.DefaultFileService$downloadFile$1.invokeSuspend(Unknown Source:18)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@67beb7f, Dispatchers.Main.immediate]
2022-12-20 15:57:15.201 27473-27473/im.vector.app.debug E/JitsiMeetLogger: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.io.IOException: Prepare failed.: status=0x1
        at android.media.MediaPlayer._prepare(Native Method)
        at android.media.MediaPlayer.prepare(MediaPlayer.java:1309)
        at im.vector.app.features.voicebroadcast.listening.VoiceBroadcastPlayerImpl.prepareMediaPlayer(VoiceBroadcastPlayerImpl.kt:308)
        at im.vector.app.features.voicebroadcast.listening.VoiceBroadcastPlayerImpl.access$prepareMediaPlayer(VoiceBroadcastPlayerImpl.kt:47)
        at im.vector.app.features.voicebroadcast.listening.VoiceBroadcastPlayerImpl$prepareMediaPlayer$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
        at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1413)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318)
        at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856)
        at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:806)
        at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:92)
        at kotlinx.coroutines.CompletableDeferredKt.completeWith(CompletableDeferred.kt:61)
        at org.matrix.android.sdk.internal.session.DefaultFileService.downloadFile(DefaultFileService.kt:213)
        at org.matrix.android.sdk.internal.session.DefaultFileService$downloadFile$1.invokeSuspend(Unknown Source:18)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@67beb7f, Dispatchers.Main.immediate]
```

### Your phone model

Pixel 6A

### Operating system version

Android 13

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by Florian14**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Handle the potential exceptions during a voice broadcast playback and display a message in the related tile in the timeline.

## Motivation and context

Fix #7829 

## Screenshots / GIFs

Tests on a corrupted VB (the corrupted chunk is at 4:50)

By reaching the corrupted chunk during playback:

https://user-images.githubusercontent.com/11990514/211588007-afa485ab-9ce8-4fa8-9e4d-05fb87a63818.mp4

By moving to the corrupted chunk:

https://user-images.githubusercontent.com/11990514/211588486-5716514a-fcb5-4246-bcd3-5254ed192414.mp4

## Tests

On a corrupted voice broadcast (there is no specific way to generate it):
- Seek to the corrupted chunk position OR play the voice broadcast until reaching the corrupting chunk
- Verify that the application does not crash and a message is displayed in the voice broadcast tile, no playback action should be available
- Verify that the tile is not reset after navigating into the app or playing another VB (reset after application restart is fine).

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt [hunk 1]
```diff
@@ -263,19 +263,27 @@ class VoiceBroadcastPlayerImpl @Inject constructor(
...
+                                onNextMediaPlayerStarted(mp)
+                            }
+                            is State.Error,
+                            State.Idle -> stopPlayer()
                         }
-                        State.IDLE -> stopPlayer()
+                    }
+                } catch (failure: VoiceBroadcastFailure.ListeningError.DownloadError) {
+                    isPreparingNextPlayer = false
+                    if (playingState == State.Buffering || tryOrNull { currentMediaPlayer?.isPlaying } != true) {
```
Comment (mnaturel) [inline vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt:285]: Why do we have this condition to set the state to `Error`? If we catch an Error it means there is an error whatever the current state is, am I correct?

File: vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt [hunk 2]
```diff
@@ -426,15 +446,16 @@ class VoiceBroadcastPlayerImpl @Inject constructor(
...
-                currentMediaPlayer = null
+                playingState = State.Buffering
+                prepareNextMediaPlayer()
             }
         }
 
         override fun onError(mp: MediaPlayer, what: Int, extra: Int): Boolean {
-            stop()
+            Timber.d("## Voice Broadcast | onError: what=$what, extra=$extra")
+            if (playingState == State.Buffering || tryOrNull { currentMediaPlayer?.isPlaying } != true) {
```
Comment (mnaturel) [inline vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt:456]: Same question about this condition.

File: vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt [hunk 3]
```diff
@@ -213,18 +214,17 @@ class VoiceBroadcastPlayerImpl @Inject constructor(
...
+                playingState = State.Error(failure)
             }
         }
     }
 
     private fun pausePlayback() {
-        playingState = State.PAUSED // This will trigger a playing state update and save the current position
+        playingState = State.Paused // This will trigger a playing state update and save the current position
         if (currentMediaPlayer != null) {
             currentMediaPlayer?.pause()
```
Comment (mnaturel) [inline vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt:229]: I see there is no `tryOrNull` on `currentMediaPlayer?.pause()` or `currentMediaPlayer?.start()`. Was it done on purpose?

File: vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt [hunk 4]
```diff
@@ -416,6 +432,10 @@ class VoiceBroadcastPlayerImpl @Inject constructor(
         }
 
         override fun onCompletion(mp: MediaPlayer) {
+            // Release media player as soon as it completed
+            mp.release()
+            currentMediaPlayer = null
```
Comment (mnaturel) [inline vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt:437]: Should we check `mp` and `currentMediaPlayer` are referencing the same instance before setting it to `null`?

**Review by mnaturel — COMMENTED** [review]
I have added small questions and thoughts.

File: vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt (hunk 1 above)
Comment (Florian14) [reply vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt:285]: In this place, the error is on the next chunk (the current one should be fine). I didn't want to display the error at this moment. When the current chunk will be ended, it will enter in buffering mode and try to prepare again the next chunk, if it fails again, it will show the error.

Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt:285]: Okay I see. Maybe we could encapsulate and mutualize this condition into a single method with a clear name to understand this intention? If the method name is not enough, we could also add a code comment.

File: vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt (hunk 3 above)
Comment (Florian14) [reply vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt:229]: Each action on the media player can trigger an exception if the player is in a bad state. The exceptions can be triggered because of a bad implementation or an internal player error (eg. a corrupted file). For the moment, I never observed calls to play/pause within a bad player state, the exceptions that I observed have been triggered when `preparing` the player, they're already caught and the play/pause actions should not be available. If the player enters in a bad state for another reason, it should also be caught by the error listener.
Do you think it would be safer to try/catch these actions or do you think I miss something when I intercept the error?

Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt:229]: I think it is okay. I just wanted to understand why it is only done in some methods. In the doc it says `pause()` may throw exception only `if the internal player engine has not been initialized.` ans `start()` may throw exception `if it is called in an invalid state`. And I think right now, it is not possible to be in these situations.

File: vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt (hunk 4 above)
Comment (Florian14) [reply vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt:437]: Not sure, what should I do if it is not the same instance? In that case, we'll be in an unexpected state. Should we stop the listening, throw an exception, release the other instance...?

File: vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt (hunk 1 above)
Comment (Florian14) [reply vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt:287]: I could not find a method name to mutualize the condition, I added a comment instead https://github.com/vector-im/element-android/pull/7919/commits/8a2f28bc376fd2f34c97270cdff7336332efe50e

File: vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt (hunk 4 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt:439]: If it is not expected, I would say we can throw error like this:
```kotlin
mp.release()
if (currentMediaPlayer == mp) {
    currentMediaPlayer = null
} else {
    throw IllegalStateException("Message to explain the situation.")
}
```
What do you think?
In the general case it will never throw except if the implementation is not correct, am I right?

Comment (Florian14) [reply vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt]: Done: https://github.com/vector-im/element-android/pull/7919/commits/169c9b221ca69039406a50744749c5336c4af85a
I did some tests and the completion is triggered before the next player starts so it should be fine.

**Review by mnaturel — APPROVED** [review]
LGTM!
