### PR TITLE
Crash on opening a room on Android 5.0 and 5.1 - Regression with Voice message

### LINKED ISSUE #3897: Crash on Android 5.0 and 5.1
Reported in https://matrix.to/#/!AZozoWghOYSIAfaZjJ:matrix.org/$y0gn7hbAap0imO-wIqO3SZ4vZsr9jEzqS9vasOPlW-o?via=matrix.org&via=tchncs.de&via=kde.org

Open a room and observe a crash. Introduce with Voice message feature.

Stack trace:

```
Thread: main, Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{im.vector.app/im.vector.app.features.home.room.detail.RoomDetailActivity}: android.view.InflateException: Binary XML file line #187: Error inflating class im.vector.app.features.home.room.detail.composer.VoiceMessageRecorderView
...
Caused by: java.lang.NullPointerException: Attempt to read from field 'android.widget.ImageButton im.vector.app.databinding.ViewVoiceMessageRecorderBinding.voiceMessageMicButton' on a null object reference
at im.vector.app.features.home.room.detail.composer.VoiceMessageRecorderView.onVisibilityChanged(VoiceMessageRecorderView.kt:4)
```

### PR DESCRIPTION
**Pull request by onurays**
Fixes #3897

### CODE REVIEW

**Comment by unclechu** [comment]
Do you have any estimation when this fix is going to be released on F-Droid?

File: vector/src/main/java/im/vector/app/features/home/room/detail/composer/VoiceMessageRecorderView.kt [hunk 1]
```diff
@@ -90,6 +96,9 @@ class VoiceMessageRecorderView @JvmOverloads constructor(
 
     override fun onVisibilityChanged(changedView: View, visibility: Int) {
         super.onVisibilityChanged(changedView, visibility)
+        // onVisibilityChanged is called by constructor on api 21 and 22.
+        if (!this::views.isInitialized) return
```
Comment (johnjohndoe) [inline vector/src/main/java/im/vector/app/features/home/room/detail/composer/VoiceMessageRecorderView.kt:100]: @bmarty Were you able to reproduce the error on Android 5 and verify if this patch works?
