### PR TITLE
Fix Rich Text Editor issues: save formatted text in draft and keep formatting when switching between modes

### LINKED ISSUE #7466: Labs: Formatting on text is lost when returning to the room list in the new WYSIWYG editor
### Steps to reproduce

1. Enable the "Enable rich text editor" in labs settings
2. Type some text and format it
3. Click the arrow in the top left to return to the room list
4. Click on the room you were just in
5. See that the formatting in your message is lost

You can see the behaviour in the below video:

https://user-images.githubusercontent.com/1342360/198073702-35d384ca-8838-4735-b2c6-70acf41a2103.mp4

#### What did you expect?

The formatting of my draft message to remain.

#### What happened instead?

My hard work is all gone!

### Your phone model

Google Pixel 4a 5G

### Operating system version

Android 13, GrapheneOS

### Application version and app store

1.5.4-dev [40105042] (F-b12018) tech/bump-wysiwyg-lib-to-0.2.1

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

- First commit: When using the RichTextEditor, store the formatted text into the Draft, to be able to restore it correctly.
- Second commit: Keep the formatted text into memory to be able to keep it when switching between composer modes.

## Motivation and context

Avoid formatting loses.

Closes #7466 

## Screenshots / GIFs

FormattedDraft

## Tests

- Enable the RichTextEditor
- Add some formatted content to the composer, and do not send the message
- go back to the room list
- open the room with the draft
- observe that the text is formatted as before.
- swipe a previous message to start replying to it
- observe that the formatting is not lost when doing that

- Disable the RichTextEditor
- observe that draft feature works like before (so no regression)

As a limitation, a draft saved with the RTE enabled can be restored a bit wildly once the RTE has been disabled. But I think this is an acceptable limitation. We may want to clear all the drafts when toggling the RTE, but user data will be lost.

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/element-hq/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/element-hq/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

**Comment by ganfra** [comment]
It looks like it's breaking some computation with the send button visibility... There is some scenarios where the send button never shows up. On develop I can't reproduce.

**Comment by bmarty** [comment]
> There is some scenarios where the send button never shows up

I cannot repro the issue of send button not visible. Can you be more precise about the scenario to repro please?

**Comment by giomfo** [comment]
> It looks like it's breaking some computation with the send button visibility... There is some scenarios where the send button never shows up. On develop I can't reproduce, but the send button is blinking when typing text (with RTE enabled).

@ganfra what is the scenario where the send button disappears? about the blinking, I think this was fixed by https://github.com/element-hq/element-android/pull/8770.
What is blocking this PR?

File: vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt [hunk 1]
```diff
@@ -151,7 +150,7 @@ class MessageComposerViewModel @AssistedInject constructor(
 
     private fun handleOnTextChanged(action: MessageComposerAction.OnTextChanged) {
         val needsSendButtonVisibilityUpdate = currentComposerText.isBlank() != action.text.isBlank()
-        currentComposerText = SpannableString(action.text)
+        currentComposerText = action.text
```
Comment (ganfra) [inline vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt:153]: @bmarty Why are u doing that? 
As it uses the CharSequence from the editor, it'll break the `needsSendButtonVisibilityUpdate` as `currentComposerText` will always be equals to `action.text`.
Reverting the change still allow to keep formatting when switching mode as far as I see.

Comment (bmarty) [reply vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt]: You're right, it is a mistake to change this. Reverted in 2395d72c93da67871c5a2d4ed61d8f93978481c0
